name: Java CI with Gradle on Arch Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: archlinux-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Build with ./gradlew
      run: ./gradlew build
